# Generated by Django 3.2.8 on 2024-11-21 13:36

from django.db import migrations, models
import django.db.models.deletion
import extinctionr.vaquita.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('vaquita', '0001_initial'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('info', '0006_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_text', models.TextField(verbose_name='hero text')),
                ('content', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul'])), ('markdown', extinctionr.vaquita.blocks.ZOrderMarkdownBlock(icon='code')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('embedded_content', wagtail.core.blocks.StructBlock([('embed', wagtail.embeds.blocks.EmbedBlock(label='url', required=True)), ('caption', wagtail.core.blocks.CharBlock(help_text='Enter a caption', label='caption')), ('use_as_hero', wagtail.core.blocks.BooleanBlock(help_text='Use as hero image', label='hero', required=False))]))])),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vaquita.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
