# Generated by Django 3.0.6 on 2020-06-13 23:57

from django.db import migrations
from ..models import Action
from extinctionr.vaquita.utils import ImageImporter


def wagtailify_action_image(apps, schema_editor):
    importer = ImageImporter("Calendar Images")
    for action in Action.objects.all():
        photos = action.photos.all()
        if not action.image and photos.count() > 0:
            photo = photos.first()  # Sorry but only supporting one image.
            action.image = importer.import_from_photo(photo)
            action.photos.clear()
            action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0023_auto_20200531_1702'),
    ]

    operations = [
        migrations.RunPython(wagtailify_action_image),
    ]
